//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thesis
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrencyRate
    {
        public CurrencyRate()
        {

        }

        public CurrencyRate(decimal sellRate, decimal buyRate, DateTime date, int id)
        {
            this.SellRate = sellRate;
            this.BuyRate = buyRate;
            this.RateDate = date;
            this.CurrencyCodeID = id;
        }


        public int ID { get; set; }
        public int CurrencyCodeID { get; set; }
        public System.DateTime RateDate { get; set; }
        public decimal SellRate { get; set; }
        public decimal BuyRate { get; set; }
    
        public virtual CurrencyCode CurrencyCode { get; set; }
    }
}
